version: '3'

services:
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/playground-realm.json
    volumes:
      - ./playground-realm.json:/tmp/playground-realm.json
      - ./login.ftl:/opt/jboss/keycloak/themes/base/login/login.ftl
      - ./target/recaptcha-login.jar:/opt/jboss/keycloak/standalone/deployments/recaptcha-login.jar
    ports:
      - 8080:8080